service_name: google_scc
title: Google Security Command Center
description: Collect logs from Google Security Command Center with Elastic Agent.
service_info:
  common_use_cases:
  - '# TODO: Add common use cases for this service'
  data_types_collected:
  - '# TODO: Add data types collected (logs, metrics, traces, etc.)'
  compatibility:
    elastic_stack_versions:
    - ^8.19.4 || ^9.1.4
    service_versions:
    - '# TODO: Add compatible service versions'
  scaling_and_performance:
    description: '# TODO: Add service performance description'
    performance_expectations:
    - '# TODO: Add typical performance expectations'
    scaling_guidance:
    - '# TODO: Add scaling recommendations'
setup_instructions:
  prerequisites:
  - '# TODO: Add service prerequisites'
  installation_steps:
  - step: 1
    title: Install Google Security Command Center
    description: '# TODO: Add Google Security Command Center installation instructions'
    commands:
    - '# TODO: Add commands to install Google Security Command Center'
kibana_setup_instructions:
  default:
    steps:
    - step: 1
      instruction: Navigate to 'Management' > 'Integrations' in Kibana.
    - step: 2
      instruction: Search for 'Google Security Command Center'.
    - step: 3
      instruction: Select and add the 'Google Security Command Center' integration.
    - step: 4
      instruction: Install Elastic Agent on the systems running Google Security Command Center, if necessary.
    - step: 5
      instruction: '# TODO: Add service-specific configuration steps'
    - step: 6
      instruction: Press 'Save Integration' to start collecting data.
troubleshooting:
  common_issues:
  - issue: Google Security Command Center fails to start
    solution: '# TODO: Add troubleshooting steps for Google Security Command Center startup issues'
  - issue: No data being collected
    solution: '# TODO: Add troubleshooting steps for data collection issues'
validation_steps:
  steps:
  - step: 1
    title: Check Google Security Command Center Service Status
    description: Verify that Google Security Command Center is running and healthy
    commands:
    - '# TODO: Add commands to check Google Security Command Center status'
    expected_output: '# TODO: Add expected output'
  - step: 2
    title: Check Integration Health
    description: Verify Elastic Agent is collecting data
    commands:
    - '# Check Elastic Agent logs for google_scc integration'
    - '# Verify data appears in Elasticsearch indices'
    expected_output: No errors in agent logs, data visible in Kibana
documentation_sites:
- '# TODO: Add relevant documentation URLs'
