service_name: prisma_access
title: Palo Alto Prisma Access
description: Collect logs from Palo Alto Prisma Access with Elastic Agent.
service_info:
  common_use_cases:
  - '# TODO: Add common use cases for this service'
  data_types_collected:
  - '# TODO: Add data types collected (logs, metrics, traces, etc.)'
  compatibility:
    elastic_stack_versions:
    - ^8.13.0 || ^9.0.0
    service_versions:
    - '# TODO: Add compatible service versions'
  scaling_and_performance:
    description: '# TODO: Add service performance description'
    performance_expectations:
    - '# TODO: Add typical performance expectations'
    scaling_guidance:
    - '# TODO: Add scaling recommendations'
setup_instructions:
  prerequisites:
  - '# TODO: Add service prerequisites'
  installation_steps:
  - step: 1
    title: Install Palo Alto Prisma Access
    description: '# TODO: Add Palo Alto Prisma Access installation instructions'
    commands:
    - '# TODO: Add commands to install Palo Alto Prisma Access'
kibana_setup_instructions:
  default:
    steps:
    - step: 1
      instruction: Navigate to 'Management' > 'Integrations' in Kibana.
    - step: 2
      instruction: Search for 'Palo Alto Prisma Access'.
    - step: 3
      instruction: Select and add the 'Palo Alto Prisma Access' integration.
    - step: 4
      instruction: Install Elastic Agent on the systems running Palo Alto Prisma Access, if necessary.
    - step: 5
      instruction: '# TODO: Add service-specific configuration steps'
    - step: 6
      instruction: Press 'Save Integration' to start collecting data.
troubleshooting:
  common_issues:
  - issue: Palo Alto Prisma Access fails to start
    solution: '# TODO: Add troubleshooting steps for Palo Alto Prisma Access startup issues'
  - issue: No data being collected
    solution: '# TODO: Add troubleshooting steps for data collection issues'
validation_steps:
  steps:
  - step: 1
    title: Check Palo Alto Prisma Access Service Status
    description: Verify that Palo Alto Prisma Access is running and healthy
    commands:
    - '# TODO: Add commands to check Palo Alto Prisma Access status'
    expected_output: '# TODO: Add expected output'
  - step: 2
    title: Check Integration Health
    description: Verify Elastic Agent is collecting data
    commands:
    - '# Check Elastic Agent logs for prisma_access integration'
    - '# Verify data appears in Elasticsearch indices'
    expected_output: No errors in agent logs, data visible in Kibana
documentation_sites:
- '# TODO: Add relevant documentation URLs'
