service_name: proofpoint_on_demand
title: Proofpoint On Demand
description: Collect logs from Proofpoint On Demand with Elastic Agent.
service_info:
  common_use_cases:
  - '# TODO: Add common use cases for this service'
  data_types_collected:
  - '# TODO: Add data types collected (logs, metrics, traces, etc.)'
  compatibility:
    elastic_stack_versions:
    - ^8.19.0 || ^9.1.0
    service_versions:
    - '# TODO: Add compatible service versions'
  scaling_and_performance:
    description: '# TODO: Add service performance description'
    performance_expectations:
    - '# TODO: Add typical performance expectations'
    scaling_guidance:
    - '# TODO: Add scaling recommendations'
setup_instructions:
  prerequisites:
  - '# TODO: Add service prerequisites'
  installation_steps:
  - step: 1
    title: Install Proofpoint On Demand
    description: '# TODO: Add Proofpoint On Demand installation instructions'
    commands:
    - '# TODO: Add commands to install Proofpoint On Demand'
kibana_setup_instructions:
  default:
    steps:
    - step: 1
      instruction: Navigate to 'Management' > 'Integrations' in Kibana.
    - step: 2
      instruction: Search for 'Proofpoint On Demand'.
    - step: 3
      instruction: Select and add the 'Proofpoint On Demand' integration.
    - step: 4
      instruction: Install Elastic Agent on the systems running Proofpoint On Demand, if necessary.
    - step: 5
      instruction: '# TODO: Add service-specific configuration steps'
    - step: 6
      instruction: Press 'Save Integration' to start collecting data.
troubleshooting:
  common_issues:
  - issue: Proofpoint On Demand fails to start
    solution: '# TODO: Add troubleshooting steps for Proofpoint On Demand startup issues'
  - issue: No data being collected
    solution: '# TODO: Add troubleshooting steps for data collection issues'
validation_steps:
  steps:
  - step: 1
    title: Check Proofpoint On Demand Service Status
    description: Verify that Proofpoint On Demand is running and healthy
    commands:
    - '# TODO: Add commands to check Proofpoint On Demand status'
    expected_output: '# TODO: Add expected output'
  - step: 2
    title: Check Integration Health
    description: Verify Elastic Agent is collecting data
    commands:
    - '# Check Elastic Agent logs for proofpoint_on_demand integration'
    - '# Verify data appears in Elasticsearch indices'
    expected_output: No errors in agent logs, data visible in Kibana
documentation_sites:
- '# TODO: Add relevant documentation URLs'
