service_name: rabbitmq
title: RabbitMQ Logs and Metrics
description: Collect and parse logs from RabbitMQ servers with Elastic Agent.
service_info:
  common_use_cases:
  - '# TODO: Add common use cases for this service'
  data_types_collected:
  - '# TODO: Add data types collected (logs, metrics, traces, etc.)'
  compatibility:
    elastic_stack_versions:
    - ^8.13.0 || ^9.0.0
    service_versions:
    - '# TODO: Add compatible service versions'
  scaling_and_performance:
    description: '# TODO: Add service performance description'
    performance_expectations:
    - '# TODO: Add typical performance expectations'
    scaling_guidance:
    - '# TODO: Add scaling recommendations'
setup_instructions:
  prerequisites:
  - '# TODO: Add service prerequisites'
  installation_steps:
  - step: 1
    title: Install RabbitMQ Logs and Metrics
    description: '# TODO: Add RabbitMQ Logs and Metrics installation instructions'
    commands:
    - '# TODO: Add commands to install RabbitMQ Logs and Metrics'
kibana_setup_instructions:
  default:
    steps:
    - step: 1
      instruction: Navigate to 'Management' > 'Integrations' in Kibana.
    - step: 2
      instruction: Search for 'RabbitMQ Logs and Metrics'.
    - step: 3
      instruction: Select and add the 'RabbitMQ Logs and Metrics' integration.
    - step: 4
      instruction: Install Elastic Agent on the systems running RabbitMQ Logs and Metrics, if necessary.
    - step: 5
      instruction: '# TODO: Add service-specific configuration steps'
    - step: 6
      instruction: Press 'Save Integration' to start collecting data.
troubleshooting:
  common_issues:
  - issue: RabbitMQ Logs and Metrics fails to start
    solution: '# TODO: Add troubleshooting steps for RabbitMQ Logs and Metrics startup issues'
  - issue: No data being collected
    solution: '# TODO: Add troubleshooting steps for data collection issues'
validation_steps:
  steps:
  - step: 1
    title: Check RabbitMQ Logs and Metrics Service Status
    description: Verify that RabbitMQ Logs and Metrics is running and healthy
    commands:
    - '# TODO: Add commands to check RabbitMQ Logs and Metrics status'
    expected_output: '# TODO: Add expected output'
  - step: 2
    title: Check Integration Health
    description: Verify Elastic Agent is collecting data
    commands:
    - '# Check Elastic Agent logs for rabbitmq integration'
    - '# Verify data appears in Elasticsearch indices'
    expected_output: No errors in agent logs, data visible in Kibana
documentation_sites:
- '# TODO: Add relevant documentation URLs'
